# Generated by Django 5.2.7 on 2025-10-22 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец брони (может быть пусто для анонимной заявки).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tables",
                to="booking.area",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="booking.table",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("area", "name")},
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["table", "datetime_start"],
                name="booking_res_table_i_8dde7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["table", "datetime_end"], name="booking_res_table_i_bb0014_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="booking_res_status_9dd5a0_idx"),
        ),
    ]
