# Generated by Django 5.2.7 on 2025-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="area",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="area",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="area",
            name="photo",
            field=models.ImageField(blank=True, upload_to="areas/"),
        ),
    ]
