# Generated by Django 5.2.7 on 2025-10-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_area_options_area_description_area_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="rotation",
        ),
        migrations.RemoveField(
            model_name="table",
            name="type",
        ),
    ]
