# Generated by Django 5.2.7 on 2025-10-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_remove_table_rotation_remove_table_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="table",
            old_name="pos_x",
            new_name="x",
        ),
        migrations.RenameField(
            model_name="table",
            old_name="pos_y",
            new_name="y",
        ),
        migrations.AddField(
            model_name="table",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="tables/"),
        ),
        migrations.AddField(
            model_name="table",
            name="photo_inactive",
            field=models.ImageField(
                blank=True, null=True, upload_to="tables/inactive/"
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "1 seat"),
                    ("2_horiz", "2 seats (horiz)"),
                    ("2_vert", "2 seats (vert)"),
                    ("4", "4 seats"),
                    ("6", "6 seats"),
                ],
                default="4",
                max_length=16,
            ),
        ),
    ]
